volumes:
  pg_data:
    driver: local
  redis_data:
    driver: local
  minio_data:
    driver: local
  nats_data:
    driver: local
  main_data:
    driver: local

services:
  db:
    build:
      context: ..
      dockerfile: docker/postgres/Dockerfile
    platform: linux/amd64
    image: registry.cn-hangzhou.aliyuncs.com/zhimaxkf/qiweidoc_db:latest
    restart: always
    shm_size: 256mb
    command: "postgres -c 'config_file=/etc/postgresql/postgresql.conf'"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      TZ: Asia/Shanghai
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - ${EXTERNAL_DB_PORT:-5432}:5432

  redis:
    build:
      context: ..
      dockerfile: docker/redis/Dockerfile
    platform: linux/amd64
    image: registry.cn-hangzhou.aliyuncs.com/zhimaxkf/qiweidoc_redis:latest
    command: [ "redis-server", "/etc/redis/redis.conf" ]
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
      - redis_data:/data
    ports:
      - ${EXTERNAL_REDIS_PORT:-6379}:6379

  minio:
    build:
      context: ..
      dockerfile: docker/minio/Dockerfile
    platform: linux/amd64
    image: registry.cn-hangzhou.aliyuncs.com/zhimaxkf/qiweidoc_minio:latest
    command: "server /data --console-address 0.0.0.0:9001"
    environment:
      TZ: Asia/Shanghai
    restart: always
    volumes:
      - minio_data:/data
    ports:
      - ${EXTERNAL_MINIO_API_PORT:-9000}:9000
      - ${EXTERNAL_MINIO_CONSOLE_PORT:-9001}:9001

  nats:
    build:
      context: ..
      dockerfile: docker/nats/Dockerfile
    platform: linux/amd64
    image: registry.cn-hangzhou.aliyuncs.com/zhimaxkf/qiweidoc_nats:latest
    command: "-js -c /etc/nats/nats-server.conf"
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
      - nats_data:/data/jetstream
    ports:
      - ${EXTERNAL_NATS_PORT:-4222}:4222

  wxfinance:
    build:
      context: ..
      dockerfile: docker/wxfinance/Dockerfile
    platform: linux/amd64
    image: registry.cn-hangzhou.aliyuncs.com/zhimaxkf/qiweidoc_wxfinance:latest
    restart: always
    environment:
      TZ: Asia/Shanghai
    depends_on:
      - nats

  httpbatch:
    build:
      context: ..
      dockerfile: docker/httpbatch/Dockerfile
    platform: linux/amd64
    image: registry.cn-hangzhou.aliyuncs.com/zhimaxkf/qiweidoc_httpbatch:latest
    restart: always
    environment:
      TZ: Asia/Shanghai
    depends_on:
      - nats

  main:
    build:
      context: ..
      dockerfile: docker/main/DockerfileDev
    platform: linux/amd64
    image: registry.cn-hangzhou.aliyuncs.com/zhimaxkf/qiweidoc_main_dev:latest
    restart: always
    command: "/usr/sbin/sshd -D"
    cpu_count: 2
    cpuset: "0,1"
    environment:
      TZ: Asia/Shanghai
    depends_on:
      - db
      - redis
      - minio
      - nats
      - wxfinance
      - httpbatch
    tty: true
    ports:
      - ${EXTERNAL_HTTP_PORT:-80}:8080
      - ${EXTERNAL_SSH_PORT:-22}:22
    volumes:
      - main_data:/var/www/

  main-prod:
    build:
      context: ..
      dockerfile: docker/main/DockerfileProd
    platform: linux/amd64
    image: registry.cn-hangzhou.aliyuncs.com/zhimaxkf/qiweidoc_main_prod:latest
    scale: 0
